//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address :.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount :.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details.
        /// </summary>
        internal static string BuyerData {
            get {
                return ResourceManager.GetString("BuyerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is cancelled by buyer..
        /// </summary>
        internal static string CancelMsg {
            get {
                return ResourceManager.GetString("CancelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment form - Checkout confirmation.
        /// </summary>
        internal static string CheckoutConfirmTitle {
            get {
                return ResourceManager.GetString("CheckoutConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment form - Checkout data.
        /// </summary>
        internal static string CheckoutTitle {
            get {
                return ResourceManager.GetString("CheckoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City :.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civility :.
        /// </summary>
        internal static string Civility {
            get {
                return ResourceManager.GetString("Civility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        internal static string CivilityMr {
            get {
                return ResourceManager.GetString("CivilityMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs..
        /// </summary>
        internal static string CivilityMrs {
            get {
                return ResourceManager.GetString("CivilityMrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        internal static string CivilityMs {
            get {
                return ResourceManager.GetString("CivilityMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you start, please make sure you changed shop identifier and keys in Web.config file..
        /// </summary>
        internal static string ConfigErrorMessage {
            get {
                return ResourceManager.GetString("ConfigErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking on the button above, the codebehind will retrieve the values entered on the previous page. These values as well as the configuration variables will be stored in a SortedDictionary in order to be sorted alphabetically..
        /// </summary>
        internal static string ConfirmDescription1 {
            get {
                return ResourceManager.GetString("ConfirmDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature processing is performed by calling the GetSignature() function in the PaymentUtils.cs API file..
        /// </summary>
        internal static string ConfirmDescription2 {
            get {
                return ResourceManager.GetString("ConfirmDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then the values will be sent to the payment gateway by calling GetPaymentForm() function..
        /// </summary>
        internal static string ConfirmDescription3 {
            get {
                return ResourceManager.GetString("ConfirmDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After payment, you will be redirected to the PaymentResult.aspx page..
        /// </summary>
        internal static string ConfirmDescription4 {
            get {
                return ResourceManager.GetString("ConfirmDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string CountryDE {
            get {
                return ResourceManager.GetString("CountryDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string CountryES {
            get {
                return ResourceManager.GetString("CountryES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string CountryFR {
            get {
                return ResourceManager.GetString("CountryFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail :.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has not been accepted. Please try to re-order..
        /// </summary>
        internal static string FailureMsg {
            get {
                return ResourceManager.GetString("FailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during the payment process..
        /// </summary>
        internal static string FatalErrorMsg {
            get {
                return ResourceManager.GetString("FatalErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name :.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field !.
        /// </summary>
        internal static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name :.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order information.
        /// </summary>
        internal static string OrderData {
            get {
                return ResourceManager.GetString("OrderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number :.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by credit card.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment form - Payment result.
        /// </summary>
        internal static string PaymentResultTitle {
            get {
                return ResourceManager.GetString("PaymentResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is now processing..
        /// </summary>
        internal static string PendingMsg {
            get {
                return ResourceManager.GetString("PendingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone :.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response content.
        /// </summary>
        internal static string ResponseContent {
            get {
                return ResourceManager.GetString("ResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature processing.
        /// </summary>
        internal static string SignatureProcessing {
            get {
                return ResourceManager.GetString("SignatureProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET payment form code sample.
        /// </summary>
        internal static string SiteHeader {
            get {
                return ResourceManager.GetString("SiteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment form.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been received. Thank you for your purchase !.
        /// </summary>
        internal static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information entered here are sent to the next page as a POST form..
        /// </summary>
        internal static string ValidateDescription {
            get {
                return ResourceManager.GetString("ValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate order.
        /// </summary>
        internal static string ValidateOrder {
            get {
                return ResourceManager.GetString("ValidateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code :.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
